// Generate resources/marronniers/data.edn from the site data file (single source of truth).
// Never edit data.edn by hand.
//
// Usage: node tools/gen_data.mjs [path/to/marronniers-2026-2027.ts]
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const DEFAULT_TS = resolve(
  ROOT,
  "../../Lescreavores/site2/nouveau-site/src/data/tool-content/marronniers-2026-2027.ts",
);
export const FIELDS = ["date", "dateFin", "libelle", "type", "secteurs", "source", "angle"];
// Clojure keyword for each source field.
export const KEYS = { date: "date", dateFin: "date-fin", libelle: "libelle", type: "type", secteurs: "secteurs", source: "source", angle: "angle" };

function literal(src, marker) {
  const start = src.indexOf(marker);
  if (start < 0) throw new Error(`marker not found: ${marker}`);
  const open = src.indexOf("[", start + marker.length - 1);
  const close = src.indexOf("\n];", open);
  if (open < 0 || close < 0) throw new Error(`array not found after ${marker}`);
  // The literal is plain JS (strings, objects, comments): evaluate it as such.
  return new Function(`return ${src.slice(open, close + 2)};`)();
}

export function parse(tsPath = DEFAULT_TS) {
  const src = readFileSync(tsPath, "utf-8");
  const entries = literal(src, "export const MARRONNIERS_2026_2027: Marronnier[] =");
  const sectors = literal(src, "export const MARRONNIER_SECTEURS: { id: string; label: string }[] =");
  const rows = (src.match(/^\s*\{ date: "/gm) || []).length;
  if (entries.length !== rows) throw new Error(`parsed ${entries.length} entries, ${rows} rows in file`);
  for (const e of entries) {
    const keys = Object.keys(e);
    if (keys.join() !== FIELDS.join()) throw new Error(`unexpected fields: ${keys.join()}`);
    for (const k of FIELDS) if (typeof e[k] !== "string") throw new Error(`non string ${k}`);
    if (!/^\d{4}-\d{2}-\d{2}$/.test(e.date) || !/^\d{4}-\d{2}-\d{2}$/.test(e.dateFin) || e.dateFin < e.date)
      throw new Error(`bad dates: ${e.date} ${e.dateFin}`);
  }
  return { entries, sectors };
}

// JSON string escapes (\" \\ \n \t \b \f \r \uXXXX) are all read by clojure.edn.
const edn = (s) => JSON.stringify(s);

function generate(tsPath) {
  const { entries, sectors } = parse(tsPath);
  const out = [
    ";; GENERATED by tools/gen_data.mjs from marronniers-2026-2027.ts (Les Créavores). Do not edit.",
    "{:sectors",
    " [" + sectors.map((s) => `{:id ${edn(s.id)} :label ${edn(s.label)}}`).join("\n  ") + "]",
    " :entries",
    " [" + entries.map((e) => `{${FIELDS.map((k) => `:${KEYS[k]} ${edn(e[k])}`).join(" ")}}`).join("\n  ") + "]}",
    "",
  ];
  const dest = resolve(ROOT, "resources/marronniers/data.edn");
  writeFileSync(dest, out.join("\n"), { encoding: "utf-8" });
  console.log(`${entries.length} entries, ${sectors.length} sectors -> ${dest}`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) generate(process.argv[2] || DEFAULT_TS);
