// Generate src/marronniers/Data.hx from the site data file (single source of truth).
// Never edit Data.hx by hand.
//
// Usage: node tools/gen_data.mjs [path/to/marronniers-2026-2027.ts]
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const DEFAULT_TS = resolve(
  ROOT,
  "../../Lescreavores/site2/nouveau-site/src/data/tool-content/marronniers-2026-2027.ts",
);
export const FIELDS = ["date", "dateFin", "libelle", "type", "secteurs", "source", "angle"];

function literal(src, marker) {
  const start = src.indexOf(marker);
  if (start < 0) throw new Error(`marker not found: ${marker}`);
  const open = src.indexOf("[", start + marker.length - 1);
  const close = src.indexOf("\n];", open);
  if (open < 0 || close < 0) throw new Error(`array not found after ${marker}`);
  // The literal is plain JS (strings, objects, comments): evaluate it as such.
  return new Function(`return ${src.slice(open, close + 2)};`)();
}

export function parse(tsPath = DEFAULT_TS) {
  const src = readFileSync(tsPath, "utf-8");
  const entries = literal(src, "export const MARRONNIERS_2026_2027: Marronnier[] =");
  const sectors = literal(src, "export const MARRONNIER_SECTEURS: { id: string; label: string }[] =");
  const rows = (src.match(/^\s*\{ date: "/gm) || []).length;
  if (entries.length !== rows) throw new Error(`parsed ${entries.length} entries, ${rows} rows in file`);
  for (const e of entries) {
    const keys = Object.keys(e);
    if (keys.join() !== FIELDS.join()) throw new Error(`unexpected fields: ${keys.join()}`);
    for (const k of FIELDS) if (typeof e[k] !== "string") throw new Error(`non string ${k}`);
    if (!/^\d{4}-\d{2}-\d{2}$/.test(e.date) || !/^\d{4}-\d{2}-\d{2}$/.test(e.dateFin) || e.dateFin < e.date)
      throw new Error(`bad dates: ${e.date} ${e.dateFin}`);
  }
  return { entries, sectors };
}

const hx = (s) => JSON.stringify(s); // JSON string escapes are valid Haxe double-quoted escapes

function generate(tsPath) {
  const { entries, sectors } = parse(tsPath);
  const out = [
    "// GENERATED by tools/gen_data.mjs from marronniers-2026-2027.ts (Les Creavores). Do not edit.",
    "package marronniers;",
    "",
    "import marronniers.Marronniers.Marronnier;",
    "import marronniers.Marronniers.Sector;",
    "",
    "class Data {",
    "\tpublic static final SECTORS:Array<Sector> = [",
    ...sectors.map((s) => `\t\t{id: ${hx(s.id)}, label: ${hx(s.label)}},`),
    "\t];",
    "",
    "\tpublic static final ENTRIES:Array<Marronnier> = [",
    ...entries.map((e) => `\t\t{${FIELDS.map((k) => `${k}: ${hx(e[k])}`).join(", ")}},`),
    "\t];",
    "}",
    "",
  ];
  const dest = resolve(ROOT, "src/marronniers/Data.hx");
  writeFileSync(dest, out.join("\n"), { encoding: "utf-8" });
  console.log(`${entries.length} entries, ${sectors.length} sectors -> ${dest}`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) generate(process.argv[2] || DEFAULT_TS);
